# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runOTR <- function(Pts, masses, steps, np, tolerance) {
    .Call(`_reconstruction2D_runOTR`, Pts, masses, steps, np, tolerance)
}

